#!/usr/bin/env python3
"""
Local PDF Builder Module (Option A)

Rebuilds PDFs with extracted content and accessibility markers.
Injects alt text, semantic structure hints, and preserved content.

This works with local_extraction.py to create ADA-compliant output
without relying on Adobe automation or cloud APIs.

Usage:
    from local_pdf_builder import rebuild_pdf_with_extraction
    rebuild_pdf_with_extraction(
        original_pdf="input.pdf",
        extracted_content=content,  # from local_extraction.extract_pdf_content()
        alt_text_data=alt_texts,    # from vision_alt_text.py (Ollama)
        output_pdf="output_ada.pdf"
    )
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Any, Optional
import pikepdf
from pikepdf import Name, Dictionary, Array
import json


@dataclass
class AltTextEntry:
    """Alt text generated by Ollama vision for an image."""
    image_page: int
    image_index: int
    alt_text: str
    confidence: float = 1.0


def inject_alt_text_to_pdf(
    pdf_path: Path,
    alt_text_list: List[AltTextEntry],
    output_path: Path
) -> bool:
    """
    Inject alt text into a PDF's structure tree (if it exists) or create basic markers.
    
    Args:
        pdf_path: Path to input PDF
        alt_text_list: List of alt text entries from Ollama
        output_path: Path to output PDF
    
    Returns:
        True if successful, False otherwise
    """
    try:
        with pikepdf.open(pdf_path) as pdf:
            struct_tree = pdf.Root.get("/StructTreeRoot")
            
            if not struct_tree:
                print("  Note: PDF has no structure tree. Alt text will be limited.")
                # For untagged PDFs, we can add inline content hints
                # This is a fallback — ideally PDFs should be tagged first
                pdf.save(output_path)
                return False
            
            # Traverse structure tree and inject alt text where appropriate
            alt_text_by_image = {
                (alt.image_page, alt.image_index): alt.alt_text
                for alt in alt_text_list
            }
            
            image_counter = {}  # Track images per page
            
            def inject_in_node(node, page_num=None):
                """Recursively inject alt text into structure tree."""
                if node is None:
                    return
                
                # Handle arrays
                if isinstance(node, (Array, list)):
                    for item in node:
                        inject_in_node(item, page_num)
                    return
                
                # Handle dictionaries
                if not isinstance(node, Dictionary) and not hasattr(node, 'get'):
                    return
                
                try:
                    elem_type = node.get("/S")
                except Exception:
                    return
                
                # If this is a Figure, try to inject alt text
                if elem_type == Name("/Figure"):
                    if page_num not in image_counter:
                        image_counter[page_num] = 0
                    else:
                        image_counter[page_num] += 1
                    
                    key = (page_num, image_counter[page_num])
                    if key in alt_text_by_image:
                        try:
                            alt_text = alt_text_by_image[key]
                            node["/Alt"] = alt_text
                            print(f"  ✓ Injected alt text for image page {page_num} index {image_counter[page_num]}")
                        except Exception as e:
                            print(f"  Warning: Could not inject alt text: {e}")
                
                # Recurse into children
                try:
                    children = node.get("/K")
                except Exception:
                    children = None
                
                if children:
                    inject_in_node(children, page_num)
            
            # Process structure tree for all pages
            k_array = struct_tree.get("/K")
            if k_array:
                for page_num in range(1, len(pdf.pages) + 1):
                    inject_in_node(k_array, page_num)
            
            pdf.save(output_path)
            print(f"✓ Alt text injected: {output_path}")
            return True
    
    except Exception as e:
        print(f"✗ Error injecting alt text: {e}")
        return False


def add_metadata_for_compliance(
    pdf_path: Path,
    title: str,
    language: str = "en-US",
    output_path: Optional[Path] = None
) -> Path:
    """
    Add minimal metadata for ADA compliance.
    
    Args:
        pdf_path: Path to input PDF
        title: Document title (will be set if missing)
        language: Language code (default: en-US)
        output_path: Path to output (default: same as input)
    
    Returns:
        Path to output PDF
    """
    if output_path is None:
        output_path = pdf_path
    
    try:
        with pikepdf.open(pdf_path) as pdf:
            # Set title
            if not pdf.Root.get("/Title"):
                pdf.Root["/Title"] = title
            
            # Set language
            if not pdf.Root.get("/Lang"):
                pdf.Root["/Lang"] = language
            
            # Set DisplayDocTitle for viewer
            if not pdf.Root.get("/ViewerPreferences"):
                pdf.Root["/ViewerPreferences"] = Dictionary()
            pdf.Root["/ViewerPreferences"]["/DisplayDocTitle"] = True
            
            # Set MarkInfo (indicates tagged PDF intent, even if not fully tagged)
            if not pdf.Root.get("/MarkInfo"):
                pdf.Root["/MarkInfo"] = Dictionary()
            pdf.Root["/MarkInfo"]["/Marked"] = True
            
            pdf.save(output_path)
            print(f"✓ Metadata added: {output_path}")
    
    except Exception as e:
        print(f"✗ Error adding metadata: {e}")
    
    return output_path


def rebuild_pdf_with_extraction(
    original_pdf: Path,
    extracted_content: 'PDFContent',  # Type hint from local_extraction.py
    alt_text_data: Optional[List[Dict[str, Any]]] = None,
    output_pdf: Optional[Path] = None
) -> bool:
    """
    Main workflow: rebuild a PDF with extracted content and alt text.
    
    This is the integration point for Option A:
    1. Take original PDF
    2. Inject Ollama-generated alt text into structure tree
    3. Add compliance metadata
    4. Output ADA-compliant PDF
    
    Args:
        original_pdf: Path to original PDF
        extracted_content: PDFContent object from local_extraction.extract_pdf_content()
        alt_text_data: List of alt text dicts from vision_alt_text.py (Ollama results)
        output_pdf: Path to output (default: same dir with _ada suffix)
    
    Returns:
        True if successful, False otherwise
    """
    original_pdf = Path(original_pdf)
    
    if output_pdf is None:
        output_pdf = original_pdf.parent / f"{original_pdf.stem}_ada.pdf"
    
    output_pdf = Path(output_pdf)
    
    print(f"\n{'='*70}")
    print(f"Rebuilding PDF with local extraction")
    print(f"  Input:  {original_pdf.name}")
    print(f"  Output: {output_pdf.name}")
    print(f"{'='*70}")
    
    try:
        # Step 1: Copy original PDF as base
        import shutil
        shutil.copy2(original_pdf, output_pdf)
        print("✓ Base PDF copied")
        
        # Step 2: Add compliance metadata
        add_metadata_for_compliance(
            output_pdf,
            title=extracted_content.metadata.get("title") or original_pdf.stem,
            language="en-US"
        )
        
        # Step 3: Inject alt text from Ollama (if available)
        if alt_text_data:
            print(f"✓ Processing {len(alt_text_data)} alt text entries from Ollama...")
            
            # Convert alt text data to AltTextEntry objects
            alt_entries = []
            for entry in alt_text_data:
                if isinstance(entry, dict):
                    alt_entries.append(AltTextEntry(
                        image_page=entry.get("page", 1),
                        image_index=entry.get("image_index", 0),
                        alt_text=entry.get("alt_text", ""),
                        confidence=entry.get("confidence", 1.0)
                    ))
            
            inject_alt_text_to_pdf(output_pdf, alt_entries, output_pdf)
        else:
            print("  Note: No alt text data provided (Ollama results not available)")
        
        print(f"\n✓ PDF rebuild complete: {output_pdf}")
        return True
    
    except Exception as e:
        print(f"✗ PDF rebuild failed: {e}")
        return False


def load_ollama_results(json_path: Path) -> Optional[List[Dict[str, Any]]]:
    """
    Load alt text results from Ollama vision processing (vision_alt_text.py output).
    
    Args:
        json_path: Path to JSON file with alt text entries
    
    Returns:
        List of alt text dicts or None if not found/failed
    """
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data.get("results", [])
    except Exception as e:
        print(f"Warning: Could not load Ollama results: {e}")
        return None


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python local_pdf_builder.py <original_pdf> [ollama_json]")
        sys.exit(1)
    
    pdf_file = Path(sys.argv[1])
    ollama_json = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    
    # Import local_extraction to get PDFContent
    from local_extraction import extract_pdf_content
    
    # Extract content
    content = extract_pdf_content(pdf_file)
    
    # Load alt text if available
    alt_text = None
    if ollama_json and ollama_json.exists():
        alt_text = load_ollama_results(ollama_json)
    
    # Rebuild
    rebuild_pdf_with_extraction(pdf_file, content, alt_text)
